name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug --output-on-failure
