name: Sync Wiki Changes to Main

on:
  gollum:
    # GitHub Wikiが更新された時に実行
  workflow_dispatch:
    # 手動実行用

jobs:
  sync-wiki-to-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          path: main-repo
          
      - name: Checkout Wiki Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo
          
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Sync Wiki to Main
        run: |
          # wikiフォルダを作成（存在しない場合）
          mkdir -p main-repo/wiki
          
          # Wikiのmdファイルをコピー
          cp -r wiki-repo/*.md main-repo/wiki/ || true
          
          cd main-repo
          git add wiki/
          
          # 変更があるか確認
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Auto-sync Wiki changes to Main repo [skip ci]"
          git push
